GinierClasses/holydraw

- db-sqldump/thyrel-db.sql
- docker-compose.yml
- Added lines to load our sqldump automatically (MYSQL_DATABASE and initdb)
- Changed phpmyadmin port to 8080 (*Conflicted with MAMP*)
RESOLVE #23
> Loads SQL dump on image creation

- db-sqldump/thyrel-db.sql
- thyrel-api/thyrel-api/Controllers/TestController.cs
- thyrel-api/thyrel-api/Models/HolyDrawDbContext.cs
- thyrel-api/thyrel-api/Models/Player.cs
- thyrel-api/thyrel-api/Models/Room.cs
- thyrel-api/thyrel-api/Models/Sentence.cs
- thyrel-api/thyrel-api/Models/Session.cs
- thyrel-web/.env
- All models have been linked to sql tables
- Player
- Token
- Session
- Room
- Sentence
- Drawing
- Fixed room.cs (Id can now be null)
RESOLVE #44
> API - DB linking

- thyrel-api/thyrel-api/Controllers/ModelsControllers/RoomController.cs
- Add room function
- GetRoomById function
- GetRoomByIdentifier
- End function
RESOLVE #40
> Create room controller

- thyrel-api/thyrel-api/Controllers/ModelsControllers/PlayerController.cs
- thyrel-api/thyrel-api/Models/Player.cs
Small description or specification about your job
<details>
<summary>
Check List
</summary>
RESOLVE #39 
ajout du PlayerController.cs
faites moi savoir si par exemple on pourrais en futur envisager des methodes "SetUsername" ou "SetAvatarUrl", normalement si on suit la logique du Flow, si on crée un autre Room, on va créer un nouveau Player
</details>
> Creating Player controller

- db-sqldump/thyrel-db.sql
- thyrel-api/thyrel-api/Controllers/ModelsControllers/PlayerController.cs
- thyrel-api/thyrel-api/Controllers/ModelsControllers/RoomController.cs
- thyrel-api/thyrel-api/Controllers/ModelsControllers/TokenController.cs
- thyrel-api/thyrel-api/Controllers/TestController.cs
- thyrel-api/thyrel-api/Models/Player.cs
- thyrel-api/thyrel-api/Models/Room.cs
- thyrel-api/thyrel-api/Models/Sentence.cs
- thyrel-api/thyrel-api/Models/Token.cs
- thyrel-api/thyrel-api/Startup.cs
- thyrel-api/thyrel-api/thyrel-api.csproj
Il y avait un bug quand on récupérais les un Player il était pas possible d'avoir les tokens associé.
J'ai expliqué dans cette docs https://github.com/GinierClasses/teamproject-thyrel-team/wiki/Tuto---Recuperation-de-relation-Entity-Framework
RESOLVE #55 
<details>
<summary>
Check List
</summary>
</details>
> fix relation bug and add new dumb

- thyrel-api/thyrel-api/Controllers/TestController.cs
- thyrel-web/src/components/lobby/AppTitle.tsx
- thyrel-web/src/index.css
- thyrel-web/src/pages/Lobby.tsx
- thyrel-web/yarn.lock
- Calling this component will show our app title with selected font and colors
- /!\ Currently does not resizes to window. WIP
> Title component react

- thyrel-web/src/components/lobby/AppLayout.tsx
<details>
<summary>
Check List
</summary>
</details>
> T37 add layout

- thyrel-api/thyrel-api/Controllers/PlayerDataProvider.cs
- thyrel-api/thyrel-api/Controllers/RoomController.cs
- thyrel-api/thyrel-api/Controllers/RoomDataProvider.cs
- thyrel-api/thyrel-api/Controllers/TokenDataProvider.cs
- thyrel-api/thyrel-api/Models/WebsocketEvent.cs
- thyrel-api/thyrel-api/Program.cs
- thyrel-api/thyrel-api/Websocket/WebsocketHandler.cs
- thyrel-api/thyrel-api/Websocket/WebsocketJson.cs
- thyrel-web/src/Routes.tsx
- thyrel-web/src/hooks/RoomProvider.tsx
- thyrel-web/src/hooks/useWebsocket.tsx
- thyrel-web/src/pages/DevNav.tsx
- thyrel-web/src/pages/Home.tsx
refactor: WebsocketHandler
add: more Websocket Event
add: event  on player left
update: DevNav with bg style
update:  to be ready for the join fonctionnality
<details>
<summary>
Check List
</summary>
</details>
> rename MModelController to ModelDataProvider

- thyrel-api/thyrel-api/Controllers/ModelsControllers/SessionDataProvider.cs
Ajout du SessionDataProvider
RESOLVE #43
> add the SessionDataProvider

- thyrel-api/thyrel-api/Controllers/RoomController.cs
- thyrel-web/src/Routes.tsx
- thyrel-web/src/pages/Home.tsx
Small description or specification about your job
<details>
<summary>
Check List
</summary>
</details>
> T59 add join controller

- thyrel-api/thyrel-api/Controllers/TestController.cs
- thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
- thyrel-api/thyrel-api/Models/Element.cs
Ajout du "ElementDataProvider" avec les valeurs Async.
Utilisation  du nouveau moyen de modifié les valeurs avec EntityFramework : https://github.com/GinierClasses/teamproject-thyrel-team/wiki/Tuto-%3A-Edit-d%27une-table-avec-EntityFramework
> T71 add element data provider

- thyrel-api/test_thyrel_api/RoomDataProviderTest.cs
- thyrel-api/test_thyrel_api/TokenElementProviderTestcs.cs
- thyrel-api/thyrel-api/Controllers/TestController.cs
- thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
- thyrel-api/thyrel-api/Websocket/WebsocketJson.cs
- thyrel-web/src/hooks/RoomProvider.tsx
- thyrel-web/src/pages/ComponentTest.tsx
feat: RoomDataProviderTest is working
- AddRoomTest
- GetRoomByIdTest
- GetRoomByIdentifierTest
- EndRoomTest
ref: Changed test name in token element provider
- AddTokenTest
CLOSE #103
> RoomDataProvider .NET test

- thyrel-web/src/__tests__/PlayerCount.test.tsx
- thyrel-web/src/__tests__/UserCardList.test.tsx
- thyrel-web/src/components/PlayerCount.tsx
- thyrel-web/src/pages/ComponentTest.tsx
feat: PlayerCount react component
rem: screen.debug() in UserCardList.test.tsx
- Takes count and max props
CLOSE #87
> PlayerCount component

- thyrel-web/src/__tests__/AvatarCard.test.tsx
- thyrel-web/src/__tests__/PlayerAvatar.test.tsx
- thyrel-web/src/__tests__/PlayerCard.test.tsx
- thyrel-web/src/__tests__/PlayerCardList.test.tsx
- thyrel-web/src/__tests__/PlayerCount.test.tsx
- thyrel-web/src/components/Home/PlayerAvatar.tsx
- thyrel-web/src/components/PlayerCount.tsx
- thyrel-web/src/components/lobby/PlayerCard.tsx
- thyrel-web/src/components/lobby/PlayerCardList.tsx
- thyrel-web/src/pages/ComponentTest.tsx
- thyrel-web/src/pages/Home.tsx
A little refractoring of component names and where they are used
RESOLVE #95 
- [x ] My Pull Request point to `sprint` branch
- [x ] I move my Issue to `Review in progress`
> Renaming components

- db-sqldump/thyrel-db.sql
perf: Added indexes on column TokenKey and Identifier
CLOSE #107
> Index Identifier and TokenKey

- .gitignore
- thyrel-web/package-lock.json
- thyrel-web/src/Routes.tsx
- thyrel-web/src/components/AppLayout.tsx
- thyrel-web/src/pages/ComponentTest.tsx
- thyrel-web/src/pages/DevNav.tsx
- thyrel-web/src/pages/Home.tsx
DOUBLE PR WITH PACKAGE.LOCK BECAUSE 
SANS PACKAGE-LOCK.JSON TOUT PEUT CASSER A TOUT MOMENT PUTAIn
> T124 wrap app into applayout2

- thyrel-web/src/__tests__/PlayerForm.test.tsx
- thyrel-web/src/components/home/PlayerForm.tsx
- thyrel-web/src/pages/Home.tsx
- thyrel-web/src/setupTests.ts
- thyrel-web/src/styles/Box.tsx
- thyrel-web/src/test/handlers.ts
Augmentation des performance de Home ainsi que ajout des tests
!!! Ticket 129 pas 29 comme le nom de la branch oups
> Improve perf and add test on HomePage

- thyrel-web/src/components/room/SizePicker.tsx
- thyrel-web/src/pages/ComponentTest.tsx
- thyrel-web/src/styles/Box.tsx
- thyrel-web/yarn.lock
feat: SizePicker component
- Will display a shadow (baseColor) around button when size is selected
- 6 buttons with 6 different values of brushes
add: boxSize in Box component
CLOSE #119
> SizePicker Component

- thyrel-api/test_thyrel_api/SessionDataProviderTest.cs
- thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
Ajout de tests pour SessionDataProvider
> T102 add test session data provider

- README.md
doc: Added badges that gives useful infos on the repostory
> doc: Added badges that gives useful infos on the repostory

- thyrel-web/src/components/room/draw/DrawColorPicker.tsx
- thyrel-web/src/components/room/draw/SizePicker.tsx
- thyrel-web/src/pages/ComponentTest.tsx
1. adding onChange() 
- When SquareButton on DrawColorPicker is clicked, the clicked square become the "CurrentColor" so have the border set to white
2. using .useMemo to avoid calculate the couples of colors of the list if the list of colors if it doesn't change
3. set the border of the squareButtons to black
RESOLVE #164
> add: DrawColorPicker now change colors when you click on them

- thyrel-api/test_thyrel_api/RoomControllerTest.cs
- thyrel-api/thyrel-api/Controllers/RoomController.cs
Le test existait déjà en fait donc juste un petit refactor du get controller en y ajoutant l'authorization et en simplifiant avec uniquement l'id
> T167 refactor get controller

- thyrel-api/test_thyrel_api/PlayerControllerTest.cs
Implementing Tests for  the endpoint "Players/{id}/Kick" of Player Controller
1. A standard Kick
2. A player Not Owner of the room can't kick
3. A player not authentified can't kick
4. A player(even if owner of his room) can't kick players of others rooms
Resolve #168
> T168 create kick controller test

- thyrel-api/test_thyrel_api/RoomControllerTest.cs
testing the creation of a new room
- when you call api/room with post method
1. a new room is created
2. a new Token is created
3. a new player is created with the token and the room
RESOLVE #186
> add: adding a test for RoomController Post method

- db-sqldump/thyrel-db.sql
Résoue le ticket #207 et pas #208 ;)
Add draw image column
> T208 add drawimage column on element

- thyrel-api/thyrel-api/Controllers/ElementController.cs
feat: Does not do NextStep() if under 5 seconds timeout
CLOSE #184
> If timer is under 5 second and everyone is done with their element, don't switch.

- thyrel-web/src/components/room/StepProgress.tsx
- thyrel-web/src/components/room/book/BookPlayerList.tsx
- thyrel-web/src/pages/ComponentTest.tsx
feat: StepProgress
- Shows at which step you are
- Also shows max ammount of steps
- Shows progress graphically with the progress component
CLOSE #200
> StepLabel Component

- thyrel-api/test_thyrel_api/SessionDataProviderTest.cs
- thyrel-api/thyrel-api/Controllers/ElementController.cs
- thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
- thyrel-api/thyrel-api/Handler/SessionStepTimeout.cs
- thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
- thyrel-api/thyrel-api/Models/DTO/SessionDto.cs
- thyrel-api/thyrel-api/Models/DTO/SessionSocketDto.cs
- thyrel-web/.eslintrc
- thyrel-web/src/components/GameBar.tsx
- thyrel-web/src/components/home/PlayerForm.tsx
- thyrel-web/src/components/room/draw/CanvasDraw.tsx
- thyrel-web/src/components/room/lobby/LobbyStartAction.tsx
- thyrel-web/src/components/room/lobby/Players.tsx
- thyrel-web/src/components/room/start/StartForm.tsx
- thyrel-web/src/hooks/SessionProvider.tsx
- thyrel-web/src/hooks/useSessionStates.tsx
- thyrel-web/src/hooks/useWebsocket.tsx
- thyrel-web/src/pages/ComponentTest.tsx
- thyrel-web/src/pages/room/Start.tsx
- thyrel-web/src/types/HolyElement.type.ts
- thyrel-web/src/types/Session.type.ts
Ajout du compteur de joueur ayant terminé dans le front.
Ajout du changemenet automatic d'état quand tous le monde termine,
Attente du merge de la PR du #159 avant de merger celle-ci
> T202 send socket on element finish

- thyrel-api/test_thyrel_api/StepTimerHandlerTest.cs
- thyrel-api/thyrel-api/Controllers/ElementController.cs
- thyrel-api/thyrel-api/Controllers/RoomController.cs
- thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
- thyrel-api/thyrel-api/DataProvider/IRoomDataProvider.cs
- thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
- thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
- thyrel-api/thyrel-api/Handler/StepTimeHandler.cs
- thyrel-api/thyrel-api/Models/DTO/RoomDto.cs
- thyrel-api/thyrel-api/Models/Element.cs
- thyrel-api/thyrel-api/Models/Player.cs
- thyrel-api/thyrel-api/Models/Session.cs
Add time and Test for all styles of games.
> T189 add time for all types of games

- thyrel-api/thyrel-api/Handler/SessionStepTimeout.cs
- thyrel-web/src/components/AppTitle.tsx
- thyrel-web/src/components/GameBar.tsx
- thyrel-web/src/components/room/StepTimer.tsx
- thyrel-web/src/index.css
- thyrel-web/src/theme.ts
Upgrade styles of GameBar
**Mobile**
**Desktop**
> T239_upgrade-game-bar

- thyrel-web/src/components/canvas/DrawingCanvas.tsx
- thyrel-web/src/components/canvas/DrawingCanvasProvider.tsx
- thyrel-web/src/components/canvas/canvas.type.ts
- thyrel-web/src/components/canvas/useCanvasEventListener.tsx
- thyrel-web/src/components/room/draw/CanvasActionButtons.tsx
- thyrel-web/src/components/room/draw/DrawColorPicker.tsx
- thyrel-web/src/components/room/draw/GameCanvas.tsx
- thyrel-web/src/pages/ComponentTest.tsx
- thyrel-web/src/pages/room/Draw.tsx
wip: Added components
- Added components
- still need to render them responsive
- DrawColorPicker is not responsive yet, but is **WIP**
---
feat: Drawing page is done !
- Page is responsive
- All components have been rendered responsive too
CLOSE #183
> Drawing page

- thyrel-api/test_thyrel_api/ElementDataProviderTest.cs
- thyrel-api/thyrel-api/Controllers/ElementController.cs
- thyrel-api/thyrel-api/Controllers/TestController.cs
- thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
- thyrel-api/thyrel-api/Models/DTO/ElementDto.cs
- thyrel-web/src/hooks/SessionProvider.tsx
- thyrel-web/src/pages/room/Book.tsx
- thyrel-web/src/pages/room/Write.tsx
- thyrel-web/src/types/HolyElement.type.ts
Fix flux to always have different player drawing diffrenent sentence.
Exemple of my exemple :
> T255 fix flux

- thyrel-web/src/components/room/lobby/KickModal.tsx
- thyrel-web/src/components/room/lobby/Players.tsx
feat: Alert window has been replaced by modal
CLOSE #223
> Modal on kick instead of default alert window

- thyrel-web/src/components/home/ButtonModalJoin.tsx
- thyrel-web/src/components/home/PlayerForm.tsx
possibilité pour le player de coller directement le lien dans la modal pour join ou l'identifier seulement
> T253 possibility for player to enter link in modal

- db-sqldump/thyrel-db.sql
- thyrel-api/test_thyrel_api/MockDatabase.cs
- thyrel-api/thyrel-api/DataProvider/PlayerDataProvider.cs
- thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
- thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
- thyrel-api/thyrel-api/Models/DTO/SessionDto.cs
- thyrel-api/thyrel-api/Models/Player.cs
- thyrel-api/thyrel-api/Models/Room.cs
- thyrel-api/thyrel-api/Models/Session.cs
- thyrel-web/src/types/Session.type.ts
feat: CurrentAlbumId has been added to database
- @Melvynx please tell me if I forgot to edit some files.
CLOSE #268
> CurrentAlbumId

- reload-db.sh
- thyrel-web/src/components/GameBar.tsx
- thyrel-web/src/components/room/GameLayout.tsx
- thyrel-web/src/components/room/book/BookStartAction.tsx
- thyrel-web/src/components/room/lobby/StartButton.tsx
- thyrel-web/src/pages/room/Book.tsx
feat: Update reload-db 
- Yes is now a default answer to the prompt, which means you can press enter and it will consider it as a yes
- Added logo
feat: Waiting Book page 
- Added a gamelayout option to not display HUD
- Added on start button an option to show different texts if book=true
wip: onStart() will need to be done when NextAlbum() exists
CLOSE #260
> Waiting book page

- thyrel-web/src/hooks/AlbumProvider.tsx
- thyrel-web/src/types/HolyElement.type.ts
- thyrel-web/src/types/websocket.types.ts
> T269 album context provider

- thyrel-web/src/hooks/RoomProvider.tsx
When a player leave the right page he will be redirected to the current page
it doesn't work for the first back arrow
> T195 redirect playing player to game page

- thyrel-api/test_thyrel_api/ElementDataProviderTest.cs
- thyrel-api/test_thyrel_api/SessionDataProviderTest.cs
- thyrel-api/thyrel-api/.env
- thyrel-api/thyrel-api/Controllers/ElementController.cs
- thyrel-api/thyrel-api/Controllers/SessionController.cs
- thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
- thyrel-api/thyrel-api/DataProvider/IElementDataProvider.cs
- thyrel-api/thyrel-api/DataProvider/IPlayerDataProvider.cs
- thyrel-api/thyrel-api/DataProvider/ISessionDataProvider.cs
- thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
- thyrel-api/thyrel-api/Handler/AlbumStepTimeout.cs
- thyrel-api/thyrel-api/Handler/SessionStepTimeout.cs
- thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
- thyrel-api/thyrel-api/Models/DTO/ElementAlbumDto.cs
- thyrel-api/thyrel-api/Models/DTO/FinishElementDto.cs
- thyrel-api/thyrel-api/Models/WebsocketEvent.cs
- thyrel-web/src/components/room/book/BookStartAction.tsx
- thyrel-web/src/hooks/AlbumProvider.tsx
- thyrel-web/src/pages/room/Book.tsx
- thyrel-web/src/types/websocket.types.ts
Add data provider function to update the currentAlbumId
Add AlbumTimeout to handle automatcly new timeout
> T270 add next album controller

- thyrel-web/public/index.html
- thyrel-web/src/__tests__/BigInput.test.tsx
- thyrel-web/src/components/AppLayout.tsx
- thyrel-web/src/components/BigButton.tsx
- thyrel-web/src/components/BigInput.tsx
- thyrel-web/src/components/canvas/DrawingCanvas.tsx
- thyrel-web/src/components/home/ButtonModalJoin.tsx
- thyrel-web/src/components/home/PlayerAvatar.tsx
- thyrel-web/src/components/room/CurrentDrawImage.tsx
- thyrel-web/src/components/room/DirectiveLabel.tsx
- thyrel-web/src/components/room/StepProgress.tsx
- thyrel-web/src/components/room/book/BookPlayerAvatar.tsx
- thyrel-web/src/components/room/book/BookPlayerList.tsx
- thyrel-web/src/components/room/book/BookSentenceElement.tsx
- thyrel-web/src/components/room/draw/SizePicker.tsx
- thyrel-web/src/components/room/lobby/KickModal.tsx
- thyrel-web/src/components/room/lobby/PlayerCard.tsx
- thyrel-web/src/pages/DevNav.tsx
- thyrel-web/src/test/mui-data.ts
- thyrel-web/src/theme.ts
- Inverte secondary and primary colors
- Update BigButton with new Styles
- Update BigInput with new styles
- Update the ButtonModalJoin button
Exemples :
> T285 update btn and input components

- thyrel-web/src/components/canvas/DrawingCanvasProvider.tsx
- thyrel-web/src/components/canvas/canvas.type.ts
- thyrel-web/src/components/canvas/useCanvasEventListener.tsx
- thyrel-web/src/components/room/draw/GameCanvas.tsx
- thyrel-web/src/components/room/draw/useDisableBodyOverflow.tsx
- thyrel-web/src/pages/ComponentTest.tsx
- thyrel-web/src/pages/room/Draw.tsx
- thyrel-web/src/theme.ts
fix: disable scroll on canvas …
add: canvas now auto reszie using the parent element
add: the canvas scale resize automaticly
add: border change automaticly for mobile phone
> T287 update draw component

- thyrel-web/src/components/canvas/useCanvasPaint.tsx
- thyrel-web/src/types/canvas.types.ts
- thyrel-web/src/utils/canvas.utils.ts
add: possibilities to only add a point on canvas
> add: possibilities to only add a point on canvas

- thyrel-web/src/__tests__/PlayerForm.test.tsx
- thyrel-web/src/components/AppLayout.tsx
- thyrel-web/src/components/BigButton.tsx
- thyrel-web/src/components/BigInput.tsx
- thyrel-web/src/components/home/ButtonModalJoin.tsx
- thyrel-web/src/components/home/PlayerForm.tsx
- thyrel-web/src/index.css
- thyrel-web/src/pages/Home.tsx
- thyrel-web/src/theme.ts
> T282 update home page

- thyrel-web/src/components/home/ButtonModalJoin.tsx
- thyrel-web/src/components/room/book/BookMock.tsx
- thyrel-web/src/components/room/book/BookSentenceElement.tsx
- thyrel-web/src/pages/ComponentTest.tsx
> T295 update BookSentenceElement

- thyrel-web/src/components/home/ButtonModalJoin.tsx
HomePage : pas d'icone et pas de couleur
JoinPage : icone & couleur
> T312 update button join w/ identifier

- thyrel-web/src/Routes.tsx
- thyrel-web/src/components/GameBar.tsx
- thyrel-web/src/components/room/GameLayout.tsx
- thyrel-web/src/components/room/StepProgress.tsx
- thyrel-web/src/components/room/StepTimer.tsx
- thyrel-web/src/pages/room/Book.tsx
- update layout for applayout and gamelayout
> T292: update app and game layout

- thyrel-web/src/components/canvas/DrawingCanvasContext.tsx
- thyrel-web/src/components/canvas/DrawingCanvasProvider.tsx
- thyrel-web/src/components/canvas/useCanvasPaint.tsx
- thyrel-web/src/components/room/draw/CanvasLineTypeButtons.tsx
- thyrel-web/src/components/room/draw/DrawColorPicker.tsx
- thyrel-web/src/components/room/draw/GameCanvas.tsx
- thyrel-web/src/types/canvas.types.ts
- thyrel-web/src/utils/canvas.utils.ts
Create the bucket tool
https://user-images.githubusercontent.com/56388157/116810712-9ffa3480-ab45-11eb-98e3-41c00a2e68e5.mp4
> T315: Create the bucket tool

- thyrel-api/thyrel-api/Controllers/SessionController.cs
- thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
- thyrel-api/thyrel-api/Models/DTO/SessionSocketDto.cs
- ajout d'un DTO pour envoyé uniquement le currentalbumid
- ajout d'un event qui prend le dto en params
- ajout de l'appel websocket dans le controller
> T297: add: websocket on album start with new currentlabumid

- thyrel-web/src/components/room/lobby/PlayerCard.tsx
feat: PlayerCardV2 is done 
- Changed background
- Changed border radius
- Removed border color
- Added shadow on avatar
CLOSE #302
> PlayerCardV2

- thyrel-web/package-lock.json
- thyrel-web/package.json
- thyrel-web/src/components/room/draw/DrawColorPicker.tsx
- thyrel-web/src/components/room/draw/PreciseColorPicker.tsx
- thyrel-web/src/components/room/draw/RandomColor.tsx
feat: color picker react
https://user-images.githubusercontent.com/50820503/117613853-ca607900-b167-11eb-9d95-134f085859b2.mov
CLOSE #293
> Color picker react

- db-sqldump/thyrel-db.sql
feat: SQL file has been updated to schema
CLOSE #347
> New SQL table (Reaction) and new cell in room table (Mode)

- thyrel-web/src/components/room/lobby/SettingsMenu.tsx
- thyrel-web/src/components/room/lobby/ShareRoomButton.tsx
refresh button for the token in shareroombutton
> T342: add refresh button

- thyrel-api/test_thyrel_api/RoomControllerTest.cs
- thyrel-api/test_thyrel_api/RoomDataProviderTest.cs
- thyrel-api/thyrel-api/Controllers/RoomController.cs
- thyrel-api/thyrel-api/DataProvider/IRoomDataProvider.cs
- thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
- thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
- thyrel-api/thyrel-api/Models/DTO/RoomDto.cs
- thyrel-api/thyrel-api/Models/WebsocketEvent.cs
- add edit room controller
- add tests
> T350 add controller for roommode

- thyrel-web/src/components/HolyDrawLogo.tsx
- thyrel-web/src/components/canvas/DrawingCanvas.tsx
- thyrel-web/src/components/canvas/useCanvasEventListener.tsx
- thyrel-web/src/components/canvas/useCanvasPaint.tsx
- thyrel-web/src/components/room/draw/desktop/DrawDesktopCanvas.tsx
- thyrel-web/src/components/room/draw/desktop/SizePickerV2.tsx
- thyrel-web/src/components/room/draw/useDisableBodyOverflow.tsx
- thyrel-web/src/hooks/useMobileHorizontal.ts
- thyrel-web/src/pages/ComponentTest.tsx
- thyrel-web/src/pages/Home.tsx
- thyrel-web/src/styles/breakpoint.ts
checez les issues
- bug: si la phrase est trop longue ça casse le layout du draw #368
- Change CMD+C to C to clear canvas #370
- fix: canvas for desktop with no scrolling on drawing #372
- fix: canvas size for more big desktop screen #374
- fix: style to match with small height desktop #375
> T368 t372 t374 t375 t370 some fix

- thyrel-api/test_thyrel_api/MockDatabase.cs
- thyrel-api/thyrel-api/Controllers/ElementController.cs
- thyrel-api/thyrel-api/DataProvider/IReactionDataProvider.cs
- thyrel-api/thyrel-api/DataProvider/ReactionDataProvider.cs
- thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
- thyrel-api/thyrel-api/Models/WebsocketEvent.cs
Creation de:
- endpoint dans ElementController pour add et remove une reaction à un élément
- ReactionDataProvider pour affecter les ajouts et délétions de la BD
- websocket pour renvoyer au front le message de suppression ou ajout de reaction
Resolve #346
> T346 reaction element controller reaction data provider

- thyrel-web/src/components/room/book/BookDrawingElement.tsx
- thyrel-web/src/components/room/start/SentenceForm.tsx
- ajout d'une height fix pour le bookdrawingelement
- si one word : longueur max + espaces impossibles
> T351 restrictions one word + T362

- thyrel-web/src/components/room/lobby/ModeCard.tsx
- thyrel-web/src/components/room/lobby/ModeModal.tsx
- thyrel-web/src/components/room/lobby/RoomModeSelector.tsx
- thyrel-web/src/components/room/lobby/SettingsMenu.tsx
- thyrel-web/src/pages/ComponentTest.tsx
ajout du selecteur de mode
ajout de la modal pour sélectionner le mode
> T365 366 room mode implementation

- thyrel-web/src/components/room/start/SentenceForm.tsx
permettre de save avec la touche enter sur la start et writepage
> T361 save with enter

- thyrel-web/src/components/room/lobby/ModeCard.tsx
Changer la Card en utilisant Card de material-ui au lieu de la box
> T387 adapt mode card

- thyrel-api/thyrel-api/Websocket/WebsocketHandler.cs
- thyrel-web/src/components/room/WebsocketStateDebug.tsx
- thyrel-web/src/components/room/lobby/SettingsMenu.tsx
- thyrel-web/src/components/room/start/SentenceForm.tsx
- thyrel-web/src/hooks/WebsocketProvider.tsx
modification de l'emplacement du machin avec écrit "vous êtes connecté" dans un truc relative en bah
> T389 add absolute debug panel
